import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export function useLanguage() {
  return useContext(LanguageContext);
}

const translations = {
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.classes': 'Classes',
    'nav.create': 'Criar',
    'nav.performance': 'Desempenho',
    'nav.logout': 'Sair',
    'nav.login': 'Entrar',
    
    // Auth
    'auth.title': 'Flashcards com IA',
    'auth.subtitle': 'Aprenda de forma inteligente com flashcards gerados por IA',
    'auth.loginGoogle': 'Entrar com Google',
    'auth.loginSuccess': 'Login realizado com sucesso!',
    'auth.logoutSuccess': 'Logout realizado com sucesso!',
    'auth.loginError': 'Erro ao fazer login. Tente novamente.',
    
    // Home
    'home.welcome': 'Bem-vindo ao Flashcards com IA',
    'home.description': 'Crie e estude flashcards personalizados gerados por inteligência artificial',
    'home.recentClasses': 'Classes Recentes',
    'home.createFirst': 'Crie sua primeira classe de flashcards!',
    'home.noClasses': 'Você ainda não tem classes criadas.',
    
    // Classes
    'classes.title': 'Minhas Classes',
    'classes.empty': 'Nenhuma classe encontrada',
    'classes.createNew': 'Criar Nova Classe',
    'classes.cards': 'cartões',
    'classes.lastStudied': 'Estudado pela última vez:',
    'classes.never': 'Nunca',
    'classes.study': 'Estudar',
    'classes.edit': 'Editar',
    'classes.delete': 'Excluir',
    
    // Create
    'create.title': 'Criar Nova Classe',
    'create.theme': 'Explique como você quer que os cartões de estudo sejam gerados',
    'create.themePlaceholder': 'Ex: Palavras básicas de japonês (1 palavra por cartão)',
    'create.numCards': 'Número de Cartões',
    'create.generate': 'Gerar Flashcards',
    'create.generating': 'Gerando...',
    'create.success': 'Flashcards gerados com sucesso!',
    'create.error': 'Erro ao gerar flashcards. Tente novamente.',
    
    // Study
    'study.title': 'Estudando',
    'study.card': 'Cartão',
    'study.of': 'de',
    'study.showAnswer': 'Mostrar Resposta',
    'study.correct': 'Correto',
    'study.incorrect': 'Incorreto',
    'study.next': 'Próximo',
    'study.finish': 'Finalizar',
    'study.completed': 'Estudo Concluído!',
    'study.accuracy': 'Precisão',
    'study.time': 'Tempo',
    'study.backToClasses': 'Voltar às Classes',
    
    // Performance
    'performance.title': 'Desempenho',
    'performance.selectClass': 'Selecione uma Classe',
    'performance.bestScore': 'Melhor Pontuação',
    'performance.accuracy': 'Precisão',
    'performance.time': 'Tempo',
    'performance.evolution': 'Evolução ao Longo do Tempo',
    'performance.cardErrors': 'Cartões com Mais Erros',
    'performance.noData': 'Nenhum dado de desempenho encontrado para esta classe.',
    
    // Edit
    'edit.title': 'Editar Classe',
    'edit.front': 'Frente',
    'edit.back': 'Verso',
    'edit.save': 'Salvar',
    'edit.cancel': 'Cancelar',
    'edit.addCard': 'Adicionar Cartão',
    'edit.deleteCard': 'Excluir Cartão',
    'edit.saved': 'Alterações salvas com sucesso!',
    
    // General
    'general.loading': 'Carregando...',
    'general.error': 'Erro',
    'general.success': 'Sucesso',
    'general.cancel': 'Cancelar',
    'general.confirm': 'Confirmar',
    'general.save': 'Salvar',
    'general.edit': 'Editar',
    'general.delete': 'Excluir',
    'general.back': 'Voltar'
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.classes': 'Classes',
    'nav.create': 'Create',
    'nav.performance': 'Performance',
    'nav.logout': 'Logout',
    'nav.login': 'Login',
    
    // Auth
    'auth.title': 'AI Flashcards',
    'auth.subtitle': 'Learn smartly with AI-generated flashcards',
    'auth.loginGoogle': 'Login with Google',
    'auth.loginSuccess': 'Login successful!',
    'auth.logoutSuccess': 'Logout successful!',
    'auth.loginError': 'Login error. Please try again.',
    
    // Home
    'home.welcome': 'Welcome to AI Flashcards',
    'home.description': 'Create and study personalized flashcards generated by artificial intelligence',
    'home.recentClasses': 'Recent Classes',
    'home.createFirst': 'Create your first flashcard class!',
    'home.noClasses': 'You haven\'t created any classes yet.',
    
    // Classes
    'classes.title': 'My Classes',
    'classes.empty': 'No classes found',
    'classes.createNew': 'Create New Class',
    'classes.cards': 'cards',
    'classes.lastStudied': 'Last studied:',
    'classes.never': 'Never',
    'classes.study': 'Study',
    'classes.edit': 'Edit',
    'classes.delete': 'Delete',
    
    // Create
    'create.title': 'Create New Class',
    'create.theme': 'Explain how you want the flashcards to be generated',
    'create.themePlaceholder': 'e.g. Basic Japanese words (1 word per card)',
    'create.numCards': 'Number of Cards',
    'create.generate': 'Generate Flashcards',
    'create.generating': 'Generating...',
    'create.success': 'Flashcards generated successfully!',
    'create.error': 'Error generating flashcards. Please try again.',
    
    // Study
    'study.title': 'Studying',
    'study.card': 'Card',
    'study.of': 'of',
    'study.showAnswer': 'Show Answer',
    'study.correct': 'Correct',
    'study.incorrect': 'Incorrect',
    'study.next': 'Next',
    'study.finish': 'Finish',
    'study.completed': 'Study Completed!',
    'study.accuracy': 'Accuracy',
    'study.time': 'Time',
    'study.backToClasses': 'Back to Classes',
    
    // Performance
    'performance.title': 'Performance',
    'performance.selectClass': 'Select a Class',
    'performance.bestScore': 'Best Score',
    'performance.accuracy': 'Accuracy',
    'performance.time': 'Time',
    'performance.evolution': 'Evolution Over Time',
    'performance.cardErrors': 'Cards with Most Errors',
    'performance.noData': 'No performance data found for this class.',
    
    // Edit
    'edit.title': 'Edit Class',
    'edit.front': 'Front',
    'edit.back': 'Back',
    'edit.save': 'Save',
    'edit.cancel': 'Cancel',
    'edit.addCard': 'Add Card',
    'edit.deleteCard': 'Delete Card',
    'edit.saved': 'Changes saved successfully!',
    
    // General
    'general.loading': 'Loading...',
    'general.error': 'Error',
    'general.success': 'Success',
    'general.cancel': 'Cancel',
    'general.confirm': 'Confirm',
    'general.save': 'Save',
    'general.edit': 'Edit',
    'general.delete': 'Delete',
    'general.back': 'Back'
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'pt';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => {
    return translations[language][key] || key;
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'pt' ? 'en' : 'pt');
  };

  const value = {
    language,
    setLanguage,
    t,
    toggleLanguage
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}
